"""High-level command flows and preflight checks.

Ties scanning, planning, validation, session writing, and applying together so
the CLI stays thin.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from pathlib import Path

from . import output
from .committer import Committer
from .config import RunConfig, resolve_provider_credentials
from .errors import FingerprintMismatchError, PreflightError
from .git_client import GitClient
from .models import AppliedCommit, CommitPlan, WorktreeSnapshot
from .planner import ensure_applicable_plan
from .planner import plan as run_planning
from .providers import build_provider
from .scanner import scan
from .session import SessionStore


def preflight(git: GitClient, cfg: RunConfig) -> None:
    if not git.is_git_repo():
        raise PreflightError(
            "not inside a Git repository",
            hint="Run atc from within a Git working tree or pass --repo.",
        )
    markers = git.in_progress_state_files()
    if markers:
        raise PreflightError(
            f"git operation in progress: {', '.join(markers)}",
            hint="Finish or abort the in-progress operation first.",
        )
    if not git.has_commits():
        raise PreflightError(
            "repository has no commits yet",
            hint="Create an initial commit before running atc.",
        )
    if git.has_staged_changes() and not cfg.include_staged:
        raise PreflightError(
            "index has staged changes",
            hint="Unstage them, or rerun with --include-staged.",
        )
    root = git.toplevel()
    for p in cfg.paths:
        if not (root / p).exists():
            raise PreflightError(f"path does not exist: {p}")


def _active_hook(path: Path) -> bool:
    return path.is_file() and os.access(path, os.X_OK)


def _pre_commit_runner(hook: Path) -> list[str] | None:
    try:
        hook_text = hook.read_text(encoding="utf-8")
    except OSError:
        return None
    if "File generated by pre-commit" not in hook_text:
        return None
    for line in hook_text.splitlines():
        if not line.startswith("INSTALL_PYTHON="):
            continue
        try:
            python = shlex.split(line.split("=", 1)[1])[0]
        except (IndexError, ValueError):
            break
        if Path(python).is_file():
            return [python, "-m", "pre_commit"]
    executable = shutil.which("pre-commit")
    return [executable] if executable else None


def prepare_hooks(git: GitClient, cfg: RunConfig) -> None:
    """Run standard pre-commit checks once before planning when requested."""
    show = not cfg.json_output
    if cfg.no_verify or cfg.hook_mode == "skip":
        cfg.no_verify = True
        output.note("Hooks: skipped", enabled=show, style="yellow")
        return
    if cfg.hook_mode == "each":
        output.note("Hooks: Git will run them for every commit", enabled=show)
        return

    preflight(git, cfg)
    hooks_dir = git.git_dir() / "hooks"
    pre_commit_hook = hooks_dir / "pre-commit"
    if _active_hook(hooks_dir / "commit-msg"):
        output.note(
            "Hooks: commit-msg is installed, so hooks will run for every commit",
            enabled=show,
            style="yellow",
        )
        cfg.hook_mode = "each"
        return
    if not _active_hook(pre_commit_hook):
        cfg.no_verify = True
        output.note("Hooks: no pre-commit hook installed", enabled=show)
        return

    runner = _pre_commit_runner(pre_commit_hook)
    if runner is None:
        output.note(
            "Hooks: custom pre-commit hook detected, so it will run for every commit",
            enabled=show,
            style="yellow",
        )
        cfg.hook_mode = "each"
        return

    with output.step("Finding files for pre-commit...", enabled=show):
        snapshot = scan(git, cfg)
    root = git.toplevel()
    paths = sorted({
        file_change.path
        for file_change in snapshot.files
        if file_change.safety.safe and (root / file_change.path).is_file()
    })
    if not paths:
        cfg.no_verify = True
        output.note("Hooks: no changed files to check", enabled=show)
        return

    # Run formatters against the complete worktree view, not Git's partially
    # staged view (which makes pre-commit stash the rest and can conflict with
    # its own fixes). ATC will stage the planned groups again during apply.
    if cfg.include_staged:
        staged = set(git.cached_changed_paths())
        staged_rename_sources = {
            file_change.old_path
            for file_change in snapshot.files
            if file_change.status == "renamed"
            and file_change.path in staged
            and file_change.old_path
        }
        git.restore_staged(sorted((staged & set(paths)) | staged_rename_sources))

    for attempt in range(1, 4):
        with output.step(
            f"Running pre-commit once on {len(paths)} changed file(s)...", enabled=show,
        ):
            result = subprocess.run(  # noqa: S603
                [*runner, "run", "--files", *paths],
                cwd=root,
                capture_output=True,
                text=True,
            )
        hook_output = "\n".join(
            part.strip() for part in (result.stdout, result.stderr) if part.strip()
        )
        if hook_output and show:
            output.err_console.print(hook_output, markup=False)
        if result.returncode == 0:
            cfg.no_verify = True
            output.note(
                "Hooks: passed once; atomic commits will reuse that result",
                enabled=show,
                style="green",
            )
            return
        if "files were modified by this hook" in hook_output.lower() and attempt < 3:
            output.note(
                f"Hooks changed files; checking again ({attempt + 1}/3)",
                enabled=show,
                style="yellow",
            )
            continue
        raise PreflightError(
            "pre-commit checks failed",
            hint=hook_output[-4000:] or "Run pre-commit manually, fix the reported files, then retry.",
        )


def _build_plan(git: GitClient, cfg: RunConfig, store: SessionStore, session_id: str) -> CommitPlan:
    cfg = resolve_provider_credentials(cfg)
    show = not cfg.json_output
    with output.step("Scanning worktree...", enabled=show):
        snapshot = scan(git, cfg)
    store.write_snapshot(session_id, snapshot)
    provider = build_provider(cfg)
    commit_plan = run_planning(provider, git, snapshot, cfg, show_progress=show)
    store.write_plan(session_id, commit_plan)
    output.print_plan(commit_plan, snapshot, as_json=cfg.json_output)
    return commit_plan


def dry_run(git: GitClient, cfg: RunConfig) -> CommitPlan:
    """Plan only; write the plan but do not commit. Used by `atc plan`."""
    preflight(git, cfg)
    store = SessionStore(git)
    session_id = store.create()
    return _build_plan(git, cfg, store, session_id)


def _apply_with_progress(
    git: GitClient,
    cfg: RunConfig,
    store: SessionStore,
    session_id: str,
    commit_plan: CommitPlan,
    *,
    prior: list[AppliedCommit] | None = None,
    planned_snapshot: WorktreeSnapshot | None = None,
    show: bool,
) -> list[AppliedCommit]:
    """Apply while durably recording each successful commit for crash recovery."""
    prior = prior or []
    progress = list(prior)

    def on_event(index: int, total: int, group, sha: str) -> None:
        progress.append(AppliedCommit(
            group_id=group.group_id,
            message=group.message,
            sha=sha,
            status="committed",
        ))
        store.write_apply_log(session_id, progress)
        output.print_apply_progress(index, total, group, sha)

    results = Committer(git, cfg).apply(
        commit_plan,
        on_event=on_event,
        planned_snapshot=planned_snapshot,
        show_progress=show,
    )
    combined = prior + results
    store.write_apply_log(session_id, combined)
    return combined


def apply_saved(git: GitClient, cfg: RunConfig, plan_path: Path | None) -> None:
    """Apply a previously saved plan (`atc apply`)."""
    preflight(git, cfg)
    if not cfg.no_verify:
        prepare_hooks(git, cfg)
    show = not cfg.json_output
    store = SessionStore(git)
    commit_plan = store.load_plan_file(plan_path) if plan_path else store.load_latest_plan()
    if commit_plan is None:
        raise PreflightError(
            "no saved plan found",
            hint="Run `atc plan` first to create a plan, or pass --plan PATH.",
        )
    with output.step("Scanning worktree...", enabled=show):
        snapshot = scan(git, cfg)
    if snapshot.fingerprint != commit_plan.repo_fingerprint:
        raise FingerprintMismatchError(
            "worktree no longer matches the saved plan",
            hint="Rerun `atc` to create a fresh plan.",
        )
    repaired = ensure_applicable_plan(commit_plan, snapshot, cfg)
    if repaired != commit_plan:
        output.note("Repaired saved plan locally", enabled=show, style="yellow")
        commit_plan = repaired
    session_id = store.create()
    store.write_plan(session_id, commit_plan)
    store.write_snapshot(session_id, snapshot)
    store.write_backup(session_id, git.backup_patch())
    results = _apply_with_progress(
        git, cfg, store, session_id, commit_plan, show=show,
    )
    output.print_apply_result(
        results, planned_total=len(commit_plan.groups), as_json=cfg.json_output,
    )


def resume(git: GitClient, cfg: RunConfig) -> None:
    show = not cfg.json_output
    store = SessionStore(git)
    session_id = store.latest_incomplete_session()
    if session_id is None:
        raise PreflightError("no incomplete session to resume")
    commit_plan = store.load_plan_file(store.session_path(session_id) / "plan.json")
    planned_snapshot = store.load_snapshot(session_id)
    if planned_snapshot is not None and any(
        entry.xy[:1] not in {"", " ", "?"} for entry in planned_snapshot.status_entries
    ):
        cfg.include_staged = True
    if not cfg.no_verify:
        prepare_hooks(git, cfg)
    preflight(git, cfg)
    if planned_snapshot is not None:
        repaired = ensure_applicable_plan(commit_plan, planned_snapshot, cfg)
        if repaired != commit_plan:
            output.note("Repaired interrupted plan locally", enabled=show, style="yellow")
            commit_plan = repaired
            store.write_plan(session_id, commit_plan)

    done = {a.group_id for a in store.load_apply_log(session_id) if a.status == "committed"}
    remaining_groups = [g for g in commit_plan.groups if g.group_id not in done]
    if not remaining_groups:
        output.print_apply_result(store.load_apply_log(session_id), as_json=cfg.json_output)
        return

    # Do NOT compare against the original whole-repo fingerprint: once some
    # groups have been committed, HEAD has advanced and committed hunks are gone
    # from the worktree, so the original fingerprint can never match again
    # (section 18). Instead, verify that every hunk still required by the
    # remaining groups is present in the current worktree scan.
    with output.step("Scanning worktree...", enabled=show):
        snapshot = scan(git, cfg)
    reference_snapshot = planned_snapshot or snapshot
    present_fps = {h.fingerprint for f in snapshot.files if f.safety.safe for h in f.hunks}
    planned_fps = {
        h.hunk_id: h.fingerprint
        for f in reference_snapshot.files
        if f.safety.safe
        for h in f.hunks
    }
    missing = [
        hid
        for g in remaining_groups
        for hid in g.hunk_ids
        if planned_fps.get(hid) not in present_fps
    ]
    untouched_head = not done and git.head_sha() == commit_plan.base_head
    if missing and not untouched_head:
        raise FingerprintMismatchError(
            "worktree changed since the session was created; "
            f"{len(missing)} planned hunk(s) no longer match",
            hint="Rerun `atc` to create a fresh plan.",
        )
    if missing:
        output.note(
            "Recovering index state left by the interrupted apply",
            enabled=show,
            style="yellow",
        )

    remaining = CommitPlan(
        version=commit_plan.version,
        mode=commit_plan.mode,
        repo_fingerprint=commit_plan.repo_fingerprint,
        base_head=commit_plan.base_head,
        groups=remaining_groups,
        excluded=commit_plan.excluded,
        warnings=commit_plan.warnings,
    )
    prior = [a for a in store.load_apply_log(session_id) if a.group_id in done]
    store.write_backup(session_id, git.backup_patch())
    results = _apply_with_progress(
        git,
        cfg,
        store,
        session_id,
        remaining,
        prior=prior,
        planned_snapshot=planned_snapshot,
        show=show,
    )
    output.print_apply_result(
        results, planned_total=len(commit_plan.groups), as_json=cfg.json_output,
    )
