from __future__ import annotations

import shutil

from atomic_commits import flows
from atomic_commits.git_client import GitClient
from tests.integration.helpers import git, make_cfg


def test_standard_pre_commit_runs_once_and_internal_commits_skip_hooks(git_repo):
    executable = shutil.which("true")
    assert executable is not None
    (git_repo / "app.py").write_text("value = 1\n")
    git(git_repo, "add", "app.py")
    git(git_repo, "commit", "-q", "-m", "seed")
    (git_repo / "app.py").write_text("value = 2\n")
    hook = git_repo / ".git" / "hooks" / "pre-commit"
    hook.write_text(
        "#!/bin/sh\n# File generated by pre-commit\n"
        f"INSTALL_PYTHON={executable}\n"
    )
    hook.chmod(0o755)
    cfg = make_cfg(git_repo)
    cfg.hook_mode = "once"

    flows.prepare_hooks(GitClient(git_repo), cfg)

    assert cfg.no_verify is True


def test_custom_pre_commit_keeps_per_commit_hooks(git_repo):
    (git_repo / "app.py").write_text("value = 1\n")
    git(git_repo, "add", "app.py")
    git(git_repo, "commit", "-q", "-m", "seed")
    (git_repo / "app.py").write_text("value = 2\n")
    hook = git_repo / ".git" / "hooks" / "pre-commit"
    hook.write_text("#!/bin/sh\nexit 0\n")
    hook.chmod(0o755)
    cfg = make_cfg(git_repo)
    cfg.hook_mode = "once"

    flows.prepare_hooks(GitClient(git_repo), cfg)

    assert cfg.no_verify is False
    assert cfg.hook_mode == "each"


def test_pre_commit_fixes_are_checked_again(git_repo, monkeypatch):
    (git_repo / "app.py").write_text("value = 1\n")
    git(git_repo, "add", "app.py")
    git(git_repo, "commit", "-q", "-m", "seed")
    (git_repo / "app.py").write_text("value = 2\n")
    hook = git_repo / ".git" / "hooks" / "pre-commit"
    hook.write_text("#!/bin/sh\n# File generated by pre-commit\n")
    hook.chmod(0o755)
    runner = git_repo / "fix-once"
    runner.write_text(
        "#!/bin/sh\n"
        "if [ ! -f .hook-ran ]; then\n"
        "  touch .hook-ran\n"
        "  echo files were modified by this hook\n"
        "  exit 1\n"
        "fi\n"
    )
    runner.chmod(0o755)
    monkeypatch.setattr(flows, "_pre_commit_runner", lambda _hook: [str(runner)])
    cfg = make_cfg(git_repo)
    cfg.hook_mode = "once"

    flows.prepare_hooks(GitClient(git_repo), cfg)

    assert cfg.no_verify is True
    assert (git_repo / ".hook-ran").is_file()


def test_pre_commit_once_unstages_included_changes(git_repo, monkeypatch):
    (git_repo / "app.py").write_text("value = 1\n")
    git(git_repo, "add", "app.py")
    git(git_repo, "commit", "-q", "-m", "seed")
    (git_repo / "app.py").write_text("value = 2\n")
    git(git_repo, "add", "app.py")
    hook = git_repo / ".git" / "hooks" / "pre-commit"
    hook.write_text("#!/bin/sh\n# File generated by pre-commit\n")
    hook.chmod(0o755)
    runner = git_repo / "check-index"
    runner.write_text("#!/bin/sh\ngit diff --cached --quiet\n")
    runner.chmod(0o755)
    monkeypatch.setattr(flows, "_pre_commit_runner", lambda _hook: [str(runner)])
    cfg = make_cfg(git_repo, include_staged=True)

    flows.prepare_hooks(GitClient(git_repo), cfg)

    assert cfg.no_verify is True
    assert git(git_repo, "diff", "--cached", "--name-only").stdout == ""
